services:
  - type: web
    name: nebulacode-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
